### ISSUE TITLE
PROJ 6 failures in rangeMapper

### ISSUE THREAD

**Issue by rsbivand** [mpio-be/rangeMapper#5]
I'm testing rgdal and its reverse dependencies with PROJ 6 and -DACCEPT_USE_OF_DEPRECATED_PROJ_API_H. The CRS offered by PROJ >= 6 are changing, so that even though rgdal is still using the proj_api.h interface (for a few more months), the underlying CRS parameters are changing. Since few are using PROJ 6 yet, you have some time to fix this as rgdal will be built with < PROJ 6 metadata files in most cases. However, PROJ 6 was released 1 March, so you'll need to adapt. I suspect that you are being caught by the changes in PROJ no longer providing a default +ellps= parameter.
I attach my check files:
[00check.log](https://github.com/mpio-be/rangeMapper/files/2951401/00check.log)
[testthat.Rout.zip](https://github.com/mpio-be/rangeMapper/files/2951402/testthat.Rout.zip)

**Comment by rsbivand** [comment]
Error still present in PROJ 6.1.0

**Comment by valcu** [comment]
fixed now.
