### ISSUE TITLE
Futures: Don't use 'transparent' (use 'sequential') + 'multiprocess' is deprecated

### ISSUE THREAD

**Issue by HenrikBengtsson** [mpio-be/rangeMapper#8]
Hi.  As part of taking the **future** package to the next level, I'm narrowing down what futures may do.  This is mostly backward compatible, but one thing that needs to go is the support for `future(..., local = FALSE)`.  Most of this has already been done, cf. https://github.com/HenrikBengtsson/future/issues/382.  However, it is still used internally by `transparent` futures, which I'll keep supporting for a while, but they should only be used for debugging and troubleshooting purposes. They should never for production use  The reason for this is that `local = FALSE` introduces behavior that is an outlier in the future framework.   (This will be clarified further in the next release of **future**).

I spotted that **rangeMapper** uses 'transparent' futures in `processRanges()`:

https://github.com/mpio-be/rangeMapper/blob/8e4800bb8a301aa45fc15e0667aa2b56a4422638/R/MapProcess-methods.R#L43-L48

* [x] Could you please replace that with `sequential` future instead?

* [x] Also, please move away from deprecated 'multiprocess' - it'll become defunct in future releases.  Instead, use either 'multisession' or 'multicore', or both.  You can test for multicore support by using `parallelly::supportsMulticore()`.

**Comment by valcu** [comment]
Fixed! As suggested all parallel support setup is fully under the the user's control.

**Comment by HenrikBengtsson** [comment]
Thank you
